### ISSUE TITLE
Add spec.md to the CLI assessment

### ISSUE THREAD

**Issue by PeterBell** [learn-co-curriculum/cli-data-gem-assessment#16]
To clarify the required specs that the project should meet. Include a spec-example.md to show how to complete it

cc @aviflombaum @jmburges @aturkewi @mendelB

**Comment by pletcher** [comment]
Thanks for being a part of the Learn community!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

We want to respond as quickly as possible and be as helpful as possible, so please be sure to include steps to reproduce the issue (as best you can remember) and any pertinent details about your environment. (Are you using the Learn IDE? Coding from the ISS?) We'll figure out what's up and get back to you ASAP.

**Comment by PeterBell** [comment]
Fixed by #17
