### ISSUE TITLE
Dead video links

### ISSUE THREAD

**Issue by Dom-Mc** [learn-co-curriculum/cli-data-gem-assessment#20]
After selecting one of the following video links, you're taken to their README pages, however the MP4 links (on those pages) return 404 errors. 
- Video- CLI Data Gem Walkthrough
- Video- CLI Data Gem Walkthrough: Creating a CLI Scraper Gem
- Video- Common Anti-Patterns in CLI Data Gem
- Video- Student Example 1: Refactoring CLI Data Gem
- Video- Student Example 2: Refactoring CLI Data Gem

**Comment by AnnJohn** [comment]
hi @Dom-Mc thanks for raising this. Will update these lessons, but to watch the videos, you'll need to view the lesson in "Learn." At the bottom of the page, if you click on the "View [lesson title] in Learn and start learning to code.." the video should come through that way. Thanks!

**Comment by Dom-Mc** [comment]
Thanks for the heads up @AnnJohn!

**Comment by AnnJohn** [comment]
also, for now we updated with just the youtube links. thanks!
