### ISSUE TITLE
Links to videos return 404 error

### ISSUE THREAD

**Issue by KerryAlsace** [learn-co-curriculum/cli-data-gem-assessment#21]
![cli data gem links](https://cloud.githubusercontent.com/assets/4077226/17739059/c548abb6-6461-11e6-9135-532792de9230.png)

The links indicated in the screenshot direct you to a Github page. For the first 3 links, that page has a video link, but clicking on it directs you to a 404 error page. The last link has a section for a video, but doesn't include the video or a video link.

**Comment by AnnJohn** [comment]
we updated with just the youtube links. thanks!
