### ISSUE TITLE
Issues with `chmod`-ing a dir in the IDE?

### ISSUE THREAD

**Issue by aturkewi** [learn-co-curriculum/cli-data-gem-assessment#23]
I've seen reports that students get an issue when using `chmod` in the Learn IDE (Permission Denied error).

This _may_ be solved by running `mkdir` in the terminal rather than creating the dir from the tree: https://github.com/learn-co-curriculum/activerecord-tvshow/issues/18

Refe: https://flatiron.atlassian.net/browse/LI-309

**Comment by aturkewi** [comment]
@cjbrock have you hear complaints about this at all?

**Comment by gj** [comment]
Gonna close this for now as stale.
