### ISSUE TITLE
Encourage watching videos in advance

### ISSUE THREAD

**Issue by daniellecroxton** [learn-co-curriculum/cli-data-gem-assessment#24]
In the **Example Domains** section there is a sentence 

> There is also a video walkthrough of building a CLI Gem called Daily Deal if you're having a hard time getting started.

I think this understates the helpfulness of the video and does not indicate that watching it in advance can help with project planning and set-up. I suggest it be changed to

> There is also a video walkthrough of building a CLI Gem called Daily Deal that reviews planning, configuring, and coding a gem. You may find it beneficial to watch before starting your project.

I have attempted to adjust this myself, but get an error in processing my submission.

**Comment by gj** [comment]
Hi @daniellecroxton !

Sorry about the `Edit Lesson` failure — it's a known issue, and we're working on it!

**Comment by gj** [comment]
Fixed in #25. Thanks for raising the issue!
