### ISSUE TITLE
open ide editor not working

### ISSUE THREAD

**Issue by ghost** [learn-co-curriculum/cli-data-gem-assessment#26]
the editor is freezing up; it won't let me type, and when it does it's only taking in every other key stroke

**Comment by drakeltheryuujin** [comment]
Hi @BrittanyTinnin,

Looks like this may actually be a problem with your Learn IDE. If this is not already
resolved, send an email to support@flatironschool.com or take a look at our
help center here: http://help.learn.co/the-learn-ide.

Thanks for contributing! 💙
