### ISSUE TITLE
Broken link that sends student to another ReadMe

### ISSUE THREAD

**Issue by ivillicana** [learn-co-curriculum/cli-data-gem-assessment#34]
Point #4 under the instructions section of this ReadMe:

[Use this IDE Sandbox](https://learn.co/tracks/online-software-engineering-structured/procedural-ruby/command-line-applications/cli-applications-in-ruby). Do not close the Sandbox without completing the next step or your work will be lost.

For students in the V7 track, that link takes them to another readme, however permission will be denied for them and will be unable to access that readme. The purpose is for them to be able to open the Learn IDE Sandbox. The `sandbox` button is also not available at the top of this page. I believe the link should be directing to: `https://learn.co/tracks/full-stack-web-development-v7/intro-to-ruby-development/command-line-applications/cli-applications-in-ruby`, at least for V7 students.

**Comment by ivalentine** [comment]
This is still an issue. I encountered it with another FSWD v7 student today.

**Comment by drakeltheryuujin** [comment]
https://github.com/learn-co-curriculum/curriculum-team/blob/master/saved-replies/fixed-bug.md

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
