### ISSUE TITLE
I do not have access to the final project for CLI Data Gem 

### ISSUE THREAD

**Issue by m-gamao** [learn-co-curriculum/cli-data-gem-assessment#35]

**Comment by m-gamao** [comment]
In the instructions, there is a link to the correct Sandbox to use.  I clicked the link and it says that I do not have access to this page.  Please advise?

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
