### ISSUE TITLE
Should add in a general average for how long this lab takes

### ISSUE THREAD

**Issue by jmburges** [learn-co-curriculum/cli-data-gem-assessment#7]
So we prepare students for what they are about to do. Maybe ask @frahman5 for the averages on this lab?

**Comment by AnnJohn** [comment]
Going to close this issue

**Comment by frahman5** [comment]
@jmburges apologies for missing this. We don't really have high fidelity data on how long a lab takes a person right now. We're going to work on a notion of "Learn time," to accurately track user session times, but that's not out yet.
